services:
  cypress:
    image: cypress/included:9.4.1
    volumes:
      - ./:/var/app
      - node_modules:/var/app/node_modules
    ports:
      - "3000:3000"
    working_dir: /var/app
    command: npm run test

volumes:
  node_modules:
